model:
  input_dim: 2
  hidden_dim: 512
  num_layers: 4

dataset:
  num_samples: 100000
  scale: 2.0
  batch_size: 1024

training:
  epochs: 20
  lr: 0.001
  model_path: "models/fractal_net.pth"

generation:
  resolution: 512
  output_path: "output/fractal.png"
  preset: "mandelbrot" # options: mandelbrot, julia & sine_swirl (does not work really well)