model:
  num_frequencies: 6
  hidden_dim: 256
  num_layers: 4

dataset:
  num_samples: 100000
  scale: 2.0
  batch_size: 1024

training:
  epochs: 40
  lr: 0.001
  model_path: "model/fractal_net.pth"

generation:
  resolution: 512
  output_path: "output/fractal.png"
  preset: "julia" # options: julia, mandelbrot, burning_ship & newton